export default {
    "ILLEGAL_TODO_ID": 'ILLEGAL_TODO_ID',
    "UNKNOWN_PRIORITY": 'UNKNOWN_PRIORITY',
    "NOT_UUID": 'NOT_UUID',
    "NOT_FOUND_TODO": 'NOT_FOUND_TODO',
    "CANNOT_DELETE_TODO": 'CANNOT_DELETE_TODO',
    "EMPTY_TITLE": 'EMPTY_TITLE',
    "TOO_LONG_TITLE": 'TOO_LONG_TITLE',
}