@startuml
title todo list

actor user 

left to right direction

package "todo" {
    usecase (todoを追加する) as addTodo
    usecase (todoを編集する) as editTodo
    user --> addTodo
    addTodo --> editTodo
    user --> editTodo
    user --> (編集したtodoを保存する)
    user --> (todoを破棄する)
    user --> (完了したtodoをまとめて破棄する)
    user --> (破棄したtodoを戻す)
    user --> (破棄したtodoを削除する)
    user --> (破棄したtodoをまとめて削除する)
    user --> (todoを完了する)
}

@enduml